### ISSUE TITLE
z offset for combination with state agency datasets

### ISSUE THREAD

**Issue by benediktschwab** [OloOcki/tum-facade#1]
The [Landesamt für Digitalisierung, Breitband und Vermessung](https://geodaten.bayern.de/opengeodata/) offers a broad range of geospatial datasets (incl. ALS laser point clouds and LOD2 building models) in the coordinate system EPSG:25832. 

Compared to TUM-FAÇADE there is a constant offset in the direction of the z-axis. It would be great to have this offset value mentioned on the TUM-FAÇADE readme.

**Comment by OloOcki** [comment]
Thank you for your comment! This suggestion is really valuable; I will add it in the new release!

**Comment by benediktschwab** [comment]
Great, thanks for mentioning!
